image:
  # targetArea represents a normalized resizing approach based on the overall area the image takes up. This allows long or wide rectangles
  # be visually in alignment with squares because their area (w * h) is about the same.
  targetArea: 2304
connections:
  # A list of connections for Visio to apply to the image.
  # name: Name of the connection when reviewing the ShapeSheet
  # x: Formula for calculating the width of the image
  # y: Formula for calculating the height of the image
  - name: North
    x: Width*0.5
    y: Height*1.1
  - name: NorthEast
    x: Width*1.1
    y: Height*1.1
  - name: East
    x: Width*1.1
    y: Height*0.5
  - name: SouthEast
    x: Width*1.1
    y: Height*-0.1
  - name: South
    x: Width*0.5
    y: Height*-0.1
  - name: SouthWest
    x: Width*-0.1
    y: Height*-0.1
  - name: West
    x: Width*-0.1
    y: Height*0.5
  - name: NorthWest
    x: Width*-0.1
    y: Height*1.1
  - name: SouthOfText
    x: Width*0.5
    y: -8mm
